# Module Two Activity

For the module two activity you are required to produce coding samples in accordance with the requirements in the project guidelines and rubric. This Notebook has been pre-created as a shell for your project submission.

Once your code is complete, you will download this notebook as an HTML file by clicking **File**, then **Download As**, then **HTML (.html)** from the Jupyter menu bar. Validate that your code and final table output is rendered in the html file before submission.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Missing Blocks:</i></b> Ensure that you have clicked <b><mark>Run</mark></b> for all blocks before downloading as an HTML file or the block may be missing from your submission.</span>
</div>

### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this starter code file, replace the `data/sample_use_only/titanic_raw.csv` with the reference to your selected data from the list below:

- `data/dirty_data.csv`
- `data/business_data.csv`

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace the <mark>data/sample_use_only/titanic_raw.csv</mark> sample data path with the path to your selected data set.</span>
</div>

In [3]:
reference_file = "data/dirty_data.csv"

## Installing Required Packages
If you have additional packages that you would like to use or install, add them to the **requirements.txt** file then run the next block.

In [4]:
!pip install --upgrade pip

Requirement already satisfied: pip in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (26.1)
Collecting pip
  Downloading pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.1.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 15.7 MB/s  0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.1
    Uninstalling pip-26.1:
      Successfully uninstalled pip-26.1
Successfully installed pip-26.1.1

In [5]:
!pip install -r requirements.txt

Requirement already satisfied: ydata-profiling==4.16.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: pydantic>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.13.3)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.30.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.14.6)
Requirement already satisfied: typeguard<5,>=3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.5.1)
Requirement already satisfied: imagehash==4.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.6)
Requirement already satisfied: dacite>=1.8 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.61.0)
Requirement already satisfied: PyWavelets in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: pillow in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from phik<0.13,>=0.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.5.7)
Requirement already satisfied: patsy>=0.5.6 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: typing_extensions>=4.14.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from typeguard<5,>=3->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: attrs>=19.3.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: puremagic in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.30)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: six>=1.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.16.0)

## Import the Required Packages
If you have additional packages that you would like to import, add them here.

In [6]:
import pandas as pd
import numpy as np

## Loading the Data
After you have selected your data set that wish to wrangle, replace the reference file path in the code block at the top of this Notebook, then run the following block.

In [7]:
raw_data = pd.read_csv(reference_file)
raw_data.head()

,date,station,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,WESF,inclement_weather
0,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
1,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
2,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
3,2018-01-02T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-8.3,-16.1,-12.2,NaN,False
4,2018-01-03T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,NaN,False

# Cleaning the Data
The sections that follow have some pre-templated steps to examine and clean data. The columns or specified attributes will need to be replaced for your respective dataset that you are cleaning. You may also need to add different cleaning options from your reading as this provides an example starting point to work with your selected dataset.

***Remember to add comments as you go.***

## Columns

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the column values are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

In [8]:
raw_data.columns

Index(['date', 'station', 'PRCP', 'SNOW', 'SNWD', 'TMAX', 'TMIN', 'TOBS',
       'WESF', 'inclement_weather'],
      dtype='object')

### Renaming Columns
If any of the columns in your dataset need renamed, you can use the following examples to update your column names.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the column values selected below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example below we want to rename the `PassengerId` column `ID` and the `Pclass` column to say `Class` as we are considering merging this data with another dataset later which will use these columns as shared keys. For this task, we use the `rename()` method and pass in a dictionary mapping the column names to their new names. We can pass `inplace=True` to change our original dataframe instead of getting a new one back, or `inplace=False` to create a new dataframe to compare against our original. In the example, we are creating a new dataframe that we will use for all follow-on cleaning actions.

In [9]:
clean_data = raw_data.rename(
    columns={
        'PassengerId': 'ID',
        'Pclass': 'Class'
    }, inplace=False
)
clean_data.head()

,date,station,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,WESF,inclement_weather
0,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
1,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
2,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
3,2018-01-02T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-8.3,-16.1,-12.2,NaN,False
4,2018-01-03T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,NaN,False

## Working with Missing Values
Lets take a look at the output of `info()` method to get a quick view of additional information about the data set which can help pinpoint missing values and wrong data types.


<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example dataset, we have an index range of 891 entries or rows available in the sample dataset. Using that foundational data, we can examine the null counts to identify which columns may have null, missing or NaN values. In the example dataset, the following columns indicate potential issues in the data: Age, Cabin, and Embarked.

In [10]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               765 non-null    object
 1   station            765 non-null    object
 2   PRCP               765 non-null    float64
 3   SNOW               577 non-null    float64
 4   SNWD               577 non-null    float64
 5   TMAX               765 non-null    float64
 6   TMIN               765 non-null    float64
 7   TOBS               398 non-null    float64
 8   WESF               11 non-null     float64
 9   inclement_weather  408 non-null    object
dtypes: float64(7), object(3)
memory usage: 59.9+ KB

### isnull()
We can also use the `isnull()` method to return a dataframe of boolean values where **True** represents missing data.

In [11]:
clean_data.isnull()

,date,station,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,WESF,inclement_weather
0,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,True,True,True
2,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
760,False,False,False,False,False,False,False,False,True,False
761,False,False,False,False,False,False,False,False,True,False
762,False,False,False,False,False,False,False,False,True,False
763,False,False,False,False,False,False,False,True,True,True
764,False,False,False,False,False,False,False,True,True,True

For the example dataset, since we already saw from the `info()` method that only three columns were impacted by data issues, the output of the `isnull()` method may not be as helpful so we can limit the output for a given column to check for nulls or use the output for other cleaning functions as shown in the example below.

For your selected dataset, you can replace the Column name `Age` with your selected column that you would like to assess expanding on the dataset for additional afflicted columns for cleaning.

In [12]:
bool_series = pd.isnull(clean_data["SNOW"])
missing_age_data = clean_data[bool_series]
missing_age_data

,date,station,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,WESF,inclement_weather
9,2018-01-05T00:00:00,?,0.3,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
10,2018-01-05T00:00:00,?,0.3,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
21,2018-01-12T00:00:00,?,0.5,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
22,2018-01-12T00:00:00,?,0.5,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
25,2018-01-13T00:00:00,?,17.5,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
754,2018-12-28T00:00:00,?,11.4,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
756,2018-12-28T00:00:00,?,11.4,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
757,2018-12-29T00:00:00,?,21.3,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
758,2018-12-29T00:00:00,?,21.3,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN
759,2018-12-30T00:00:00,?,0.0,NaN,NaN,5505.0,-40.0,NaN,NaN,NaN

### Using Numpy to Find Missing Data using a Dictionary Comprehension
Rather than do this for each column, we can write a function that will use a [dictionary comprehension](https://www.python.org/dev/peps/pep-0274/) to check all the columns for us:

In [13]:
def get_nan_count(clean_data):
    return {
        col: clean_data[clean_data[col].isin([np.nan])].shape[0] for col in clean_data.columns
    }

get_nan_count(clean_data)

{'date': 0,
 'station': 0,
 'PRCP': 0,
 'SNOW': 188,
 'SNWD': 188,
 'TMAX': 0,
 'TMIN': 0,
 'TOBS': 367,
 'WESF': 754,
 'inclement_weather': 357}

###  Filling Missing Values Using fillna(), replace() and interpolate()
From the example output, there were 177 rows of data that were impacted by missing data from the sample dataset. For your selected dataset you should evaluate your columns you identified with missing or null values and expand to the afflicted columns to clean your respective dataset.

#### Filling Missing Values with a Specific Value Using fillna()
Here in the example, we will fill in the missing `Age` values with an age of `0` based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection.

In [14]:
clean_data["SNOW"].fillna('0', inplace = True )
clean_data["SNOW"] = clean_data["SNOW"].astype(float)
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               765 non-null    object
 1   station            765 non-null    object
 2   PRCP               765 non-null    float64
 3   SNOW               765 non-null    float64
 4   SNWD               577 non-null    float64
 5   TMAX               765 non-null    float64
 6   TMIN               765 non-null    float64
 7   TOBS               398 non-null    float64
 8   WESF               11 non-null     float64
 9   inclement_weather  408 non-null    object
dtypes: float64(7), object(3)
memory usage: 59.9+ KB

If you do not find the info() method helpful to find the missing data, you can use the previously created get_nan_count() we created to view the missing data by column. In the sample dataset you will see there are still two columns with null values to be addressed.

In [15]:
get_nan_count(clean_data)

{'date': 0,
 'station': 0,
 'PRCP': 0,
 'SNOW': 0,
 'SNWD': 188,
 'TMAX': 0,
 'TMIN': 0,
 'TOBS': 367,
 'WESF': 754,
 'inclement_weather': 357}

<div class="alert alert-block alert-warning">
    <span style="color:black"><b><i>Example Data:</i></b> Your selected dataset is likely to have several columns where the data is missing, create additional code blocks as necessary to clean your data according to the assignment requirements. Here we will clean the columns with different methods to show you different use cases, you will modify the code herein to the methods you feel are appropriate for your selected data set.
</div>

#### Replacing Missing Values Using replace()
Here in the example, we will replace the missing `Embarked` values with an age of `U` to represent **Unknown** based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection.

In [16]:
clean_data["SNOW"].replace(to_replace=np.nan, value='U', inplace = True )
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               765 non-null    object
 1   station            765 non-null    object
 2   PRCP               765 non-null    float64
 3   SNOW               765 non-null    float64
 4   SNWD               577 non-null    float64
 5   TMAX               765 non-null    float64
 6   TMIN               765 non-null    float64
 7   TOBS               398 non-null    float64
 8   WESF               11 non-null     float64
 9   inclement_weather  408 non-null    object
dtypes: float64(7), object(3)
memory usage: 59.9+ KB

#### Dropping Missing Values in Pandas Using dropna()
Here in the example, we will drop the column `Cabin` based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection. Keep in mind that if you use dropna() with an axis of 1, where there are nulls or missing values in more than one column, it may drop all columns that have null or missing values.

In [17]:
clean_data.drop(columns=["SNOW"], inplace = True )
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               765 non-null    object
 1   station            765 non-null    object
 2   PRCP               765 non-null    float64
 3   SNWD               577 non-null    float64
 4   TMAX               765 non-null    float64
 5   TMIN               765 non-null    float64
 6   TOBS               398 non-null    float64
 7   WESF               11 non-null     float64
 8   inclement_weather  408 non-null    object
dtypes: float64(6), object(3)
memory usage: 53.9+ KB

### Duplicated Records
Some datasets may include duplicated records. 

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the data types are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

The sample dataset does not have any duplicated records, though some code examples will be provided here for your use against your selected dataset, update the actions you would like to take against your selected dataset to clean it to your preference.

In [18]:
clean_data.duplicated()

0      False
1       True
2       True
3      False
4      False
       ...
760    False
761     True
762     True
763    False
764     True
Length: 765, dtype: bool

## Data Types
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the data types are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

You can use either the .dtypes property to view the data types for each column in the data frame, or the .info() method which will provide additional insights into the columns.

In [19]:
clean_data.dtypes

date                  object
station               object
PRCP                 float64
SNWD                 float64
TMAX                 float64
TMIN                 float64
TOBS                 float64
WESF                 float64
inclement_weather     object
dtype: object

### Data Type Conversion
If any of the data types in your dataset need to be modified or redefined, you can use the following block to update your column data types.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the columns and data types selected below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example below we want to modify the data values and type for the `Survived` column to represent a `bool`.

If you do not have any type conversions required for your data set, feel free to comment out the existing example and add a comment as applicable in the code block below:

In [22]:
clean_data = clean_data.assign(
    inclement_weather=lambda x: x.inclement_weather.astype('bool')
)
clean_data.dtypes

date                  object
station               object
PRCP                 float64
SNWD                 float64
TMAX                 float64
TMIN                 float64
TOBS                 float64
WESF                 float64
inclement_weather       bool
dtype: object

We will take a quick look at the output of the describe method.

In [24]:
clean_data.describe()

/home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages/numpy/lib/function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

             PRCP   SNWD         TMAX        TMIN        TOBS       WESF
count  765.000000  577.0   765.000000  765.000000  398.000000  11.000000
mean     5.360392    NaN  2649.175294  -15.914379    8.632161  16.290909
std     10.002138    NaN  2744.156281   24.242849    9.815054   9.489832
min      0.000000   -inf   -11.700000  -40.000000  -16.100000   1.800000
25%      0.000000    NaN    13.300000  -40.000000    0.150000   8.600000
50%      0.000000    NaN    32.800000  -11.100000    8.300000  19.300000
75%      5.800000    NaN  5505.000000    6.700000   18.300000  24.900000
max     61.700000    inf  5505.000000   23.900000   26.100000  28.700000

We will now take a look at the top five records in our dataframe before continue the cleaning examples.

In [25]:
clean_data.head()

,date,station,PRCP,SNWD,TMAX,TMIN,TOBS,WESF,inclement_weather
0,2018-01-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
1,2018-01-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
2,2018-01-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
3,2018-01-02T00:00:00,GHCND:USC00280907,0.0,-inf,-8.3,-16.1,-12.2,NaN,False
4,2018-01-03T00:00:00,GHCND:USC00280907,0.0,-inf,-4.4,-13.9,-13.3,NaN,False

### Categoricals
When choosing which columns to set as categories, you will want to evaluate how many different values are available for the column.
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

Here in the example dataset, there are three values for the `Class` column, there are two values for the `Sex` column, and three values for the `Embarked` column, so we will convert those to categories for furture analysis. All other columns aside from `Survived` column that we converted to a bool, have a variety of values which cannot be easily placed into categories without first creating bins to use as categoricals which will we learn more about in the coming modules.

In [29]:
clean_data_with_categories = clean_data.assign(
    TOBS=clean_data.TOBS.astype('category'),
    WESF=clean_data.WESF.astype('category'),
    TMIN=clean_data.TMIN.astype('category')
)
clean_data_with_categories.dtypes

date                   object
station                object
PRCP                  float64
SNWD                  float64
TMAX                  float64
TMIN                 category
TOBS                 category
WESF                 category
inclement_weather        bool
dtype: object

In [30]:
clean_data_with_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               765 non-null    object
 1   station            765 non-null    object
 2   PRCP               765 non-null    float64
 3   SNWD               577 non-null    float64
 4   TMAX               765 non-null    float64
 5   TMIN               765 non-null    category
 6   TOBS               398 non-null    category
 7   WESF               11 non-null     category
 8   inclement_weather  765 non-null    bool
dtypes: bool(1), category(3), float64(3), object(2)
memory usage: 38.5+ KB

In [31]:
clean_data_with_categories.describe()

/home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages/numpy/lib/function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

             PRCP   SNWD         TMAX
count  765.000000  577.0   765.000000
mean     5.360392    NaN  2649.175294
std     10.002138    NaN  2744.156281
min      0.000000   -inf   -11.700000
25%      0.000000    NaN    13.300000
50%      0.000000    NaN    32.800000
75%      5.800000    NaN  5505.000000
max     61.700000    inf  5505.000000

In [32]:
clean_data_with_categories.describe(include='category')

         TMIN   TOBS  WESF
count   765.0  398.0  11.0
unique   68.0   69.0   7.0
top     -40.0    0.0  24.9
freq    367.0   22.0   3.0

## Tabular Format
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output are from the sample data and will not represent your dataset until these blocks are run. Validate your table represents your dataset before activity submission.</span>
</div>

In [33]:
len(clean_data_with_categories)

765

In [34]:
pd.set_option('display.max_rows', None)
clean_data_with_categories

,date,station,PRCP,SNWD,TMAX,TMIN,TOBS,WESF,inclement_weather
0,2018-01-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
1,2018-01-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
2,2018-01-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
3,2018-01-02T00:00:00,GHCND:USC00280907,0.0,-inf,-8.3,-16.1,-12.2,NaN,False
4,2018-01-03T00:00:00,GHCND:USC00280907,0.0,-inf,-4.4,-13.9,-13.3,NaN,False
5,2018-01-03T00:00:00,GHCND:USC00280907,0.0,-inf,-4.4,-13.9,-13.3,NaN,False
6,2018-01-03T00:00:00,GHCND:USC00280907,0.0,-inf,-4.4,-13.9,-13.3,NaN,False
7,2018-01-04T00:00:00,?,20.6,inf,5505.0,-40.0,NaN,19.3,True
8,2018-01-04T00:00:00,?,20.6,inf,5505.0,-40.0,NaN,19.3,True
9,2018-01-05T00:00:00,?,0.3,NaN,5505.0,-40.0,NaN,NaN,True
10,2018-01-05T00:00:00,?,0.3,NaN,5505.0,-40.0,NaN,NaN,True
11,2018-01-05T00:00:00,GHCND:USC00280907,14.2,inf,-4.4,-13.9,-13.9,NaN,True
12,2018-01-06T00:00:00,GHCND:USC00280907,0.0,-inf,-10.0,-15.6,-15.0,NaN,False
13,2018-01-07T00:00:00,GHCND:USC00280907,0.0,-inf,-11.7,-17.2,-16.1,NaN,False
14,2018-01-07T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
15,2018-01-08T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
16,2018-01-08T00:00:00,GHCND:USC00280907,0.0,-inf,-7.8,-16.7,-8.3,NaN,False
17,2018-01-10T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
18,2018-01-10T00:00:00,GHCND:USC00280907,0.0,-inf,5.0,-7.8,-7.8,NaN,False
19,2018-01-11T00:00:00,GHCND:USC00280907,0.0,-inf,4.4,-7.8,1.1,NaN,False
20,2018-01-12T00:00:00,GHCND:USC00280907,1.3,-inf,9.4,0.6,7.8,NaN,False
21,2018-01-12T00:00:00,?,0.5,NaN,5505.0,-40.0,NaN,NaN,True
22,2018-01-12T00:00:00,?,0.5,NaN,5505.0,-40.0,NaN,NaN,True
23,2018-01-12T00:00:00,GHCND:USC00280907,1.3,-inf,9.4,0.6,7.8,NaN,False
24,2018-01-12T00:00:00,GHCND:USC00280907,1.3,-inf,9.4,0.6,7.8,NaN,False
25,2018-01-13T00:00:00,?,17.5,NaN,5505.0,-40.0,NaN,NaN,True
26,2018-01-14T00:00:00,GHCND:USC00280907,0.0,-inf,2.2,-11.1,-11.1,NaN,False
27,2018-01-14T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
28,2018-01-14T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
29,2018-01-14T00:00:00,GHCND:USC00280907,0.0,-inf,2.2,-11.1,-11.1,NaN,False
30,2018-01-15T00:00:00,GHCND:USC00280907,0.0,-inf,-5.0,-11.7,-8.9,NaN,False
31,2018-01-16T00:00:00,GHCND:USC00280907,0.0,-inf,-1.1,-9.4,-4.4,NaN,False
32,2018-01-16T00:00:00,GHCND:USC00280907,0.0,-inf,-1.1,-9.4,-4.4,NaN,False
33,2018-01-17T00:00:00,?,4.8,NaN,5505.0,-40.0,NaN,NaN,True
34,2018-01-17T00:00:00,GHCND:USC00280907,3.0,inf,0.6,-5.0,0.0,NaN,True
35,2018-01-17T00:00:00,GHCND:USC00280907,3.0,inf,0.6,-5.0,0.0,NaN,True
36,2018-01-18T00:00:00,GHCND:USC00280907,1.3,inf,0.0,-11.1,-8.9,NaN,True
37,2018-01-18T00:00:00,GHCND:USC00280907,1.3,inf,0.0,-11.1,-8.9,NaN,True
38,2018-01-18T00:00:00,GHCND:USC00280907,1.3,inf,0.0,-11.1,-8.9,NaN,True
39,2018-01-19T00:00:00,GHCND:USC00280907,0.0,-inf,-1.1,-11.7,-10.6,NaN,False
40,2018-01-19T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
41,2018-01-19T00:00:00,GHCND:USC00280907,0.0,-inf,-1.1,-11.7,-10.6,NaN,False
42,2018-01-20T00:00:00,GHCND:USC00280907,0.0,-inf,2.8,-11.7,0.0,NaN,False
43,2018-01-21T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
44,2018-01-21T00:00:00,GHCND:USC00280907,0.0,-inf,8.3,-3.3,-2.2,NaN,False
45,2018-01-22T00:00:00,?,0.3,NaN,5505.0,-40.0,NaN,NaN,True
46,2018-01-23T00:00:00,GHCND:USC00280907,18.0,-inf,8.9,2.2,5.0,NaN,False
47,2018-01-23T00:00:00,?,3.3,NaN,5505.0,-40.0,NaN,NaN,True
48,2018-01-24T00:00:00,GHCND:USC00280907,3.3,-inf,13.3,3.3,4.4,NaN,False
49,2018-01-24T00:00:00,?,5.3,NaN,5505.0,-40.0,NaN,NaN,True
50,2018-01-25T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
51,2018-01-25T00:00:00,GHCND:USC00280907,0.0,-inf,4.4,-6.7,-4.4,NaN,False
52,2018-01-26T00:00:00,GHCND:USC00280907,0.0,-inf,0.0,-7.2,-6.1,NaN,False
53,2018-01-26T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
54,2018-01-26T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
55,2018-01-27T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
56,2018-01-28T00:00:00,GHCND:USC00280907,1.5,-inf,11.1,-5.0,5.0,NaN,False
57,2018-01-28T00:00:00,GHCND:USC00280907,1.5,-inf,11.1,-5.0,5.0,NaN,False
58,2018-01-30T00:00:00,?,1.5,inf,5505.0,-40.0,NaN,1.8,True
59,2018-01-30T00:00:00,GHCND:USC00280907,0.0,-inf,6.7,-1.7,-0.6,NaN,False
60,2018-01-31T00:00:00,GHCND:USC00280907,0.0,-inf,6.7,-10.0,-8.9,NaN,False
61,2018-01-31T00:00:00,GHCND:USC00280907,0.0,-inf,6.7,-10.0,-8.9,NaN,False
62,2018-02-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
63,2018-02-01T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
64,2018-02-02T00:00:00,?,3.8,-inf,5505.0,-40.0,NaN,NaN,True
65,2018-02-02T00:00:00,?,3.8,-inf,5505.0,-40.0,NaN,NaN,True
66,2018-02-05T00:00:00,?,21.8,NaN,5505.0,-40.0,NaN,NaN,True
67,2018-02-05T00:00:00,?,21.8,NaN,5505.0,-40.0,NaN,NaN,True
68,2018-02-05T00:00:00,GHCND:USC00280907,19.8,NaN,2.8,-3.9,2.2,NaN,False
69,2018-02-05T00:00:00,GHCND:USC00280907,19.8,NaN,2.8,-3.9,2.2,NaN,False
70,2018-02-05T00:00:00,?,21.8,NaN,5505.0,-40.0,NaN,NaN,True
71,2018-02-05T00:00:00,GHCND:USC00280907,19.8,NaN,2.8,-3.9,2.2,NaN,False
72,2018-02-06T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
73,2018-02-08T00:00:00,GHCND:USC00280907,24.4,inf,3.3,-5.6,-5.6,NaN,True
74,2018-02-08T00:00:00,GHCND:USC00280907,24.4,inf,3.3,-5.6,-5.6,NaN,True
75,2018-02-08T00:00:00,?,24.6,NaN,5505.0,-40.0,NaN,NaN,True
76,2018-02-09T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
77,2018-02-09T00:00:00,GHCND:USC00280907,0.0,-inf,-1.1,-8.3,-8.3,NaN,False
78,2018-02-09T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
79,2018-02-09T00:00:00,GHCND:USC00280907,0.0,-inf,-1.1,-8.3,-8.3,NaN,False
80,2018-02-10T00:00:00,GHCND:USC00280907,0.0,-inf,0.0,-8.3,0.0,NaN,False
81,2018-02-10T00:00:00,GHCND:USC00280907,0.0,-inf,0.0,-8.3,0.0,NaN,False
82,2018-02-10T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
83,2018-02-10T00:00:00,GHCND:USC00280907,0.0,-inf,0.0,-8.3,0.0,NaN,False
84,2018-02-11T00:00:00,GHCND:USC00280907,18.0,-inf,5.0,0.0,3.3,NaN,False
85,2018-02-11T00:00:00,?,31.2,NaN,5505.0,-40.0,NaN,NaN,True
86,2018-02-11T00:00:00,GHCND:USC00280907,18.0,-inf,5.0,0.0,3.3,NaN,False
87,2018-02-12T00:00:00,GHCND:USC00280907,9.4,-inf,13.9,3.3,3.9,NaN,False
88,2018-02-13T00:00:00,GHCND:USC00280907,0.0,-inf,5.6,-5.0,-4.4,NaN,False
89,2018-02-13T00:00:00,GHCND:USC00280907,0.0,-inf,5.6,-5.0,-4.4,NaN,False
90,2018-02-14T00:00:00,?,0.5,NaN,5505.0,-40.0,NaN,NaN,True
91,2018-02-14T00:00:00,GHCND:USC00280907,0.5,-inf,2.2,-4.4,0.0,NaN,False
92,2018-02-14T00:00:00,?,0.5,NaN,5505.0,-40.0,NaN,NaN,True
93,2018-02-15T00:00:00,?,1.8,NaN,5505.0,-40.0,NaN,NaN,True
94,2018-02-15T00:00:00,GHCND:USC00280907,0.5,-inf,9.4,-0.6,5.0,NaN,False
95,2018-02-15T00:00:00,?,1.8,NaN,5505.0,-40.0,NaN,NaN,True
96,2018-02-16T00:00:00,?,3.3,NaN,5505.0,-40.0,NaN,NaN,True
97,2018-02-16T00:00:00,GHCND:USC00280907,3.3,-inf,13.3,3.3,10.0,NaN,False
98,2018-02-16T00:00:00,GHCND:USC00280907,3.3,-inf,13.3,3.3,10.0,NaN,False
99,2018-02-16T00:00:00,?,3.3,NaN,5505.0,-40.0,NaN,NaN,True
100,2018-02-17T00:00:00,?,1.5,NaN,5505.0,-40.0,NaN,NaN,True
101,2018-02-17T00:00:00,GHCND:USC00280907,0.0,-inf,13.3,-4.4,-3.3,NaN,False
102,2018-02-18T00:00:00,GHCND:USC00280907,18.8,inf,3.9,-3.9,0.6,NaN,True
103,2018-02-19T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
104,2018-02-19T00:00:00,GHCND:USC00280907,0.0,NaN,5.6,-5.0,-3.3,NaN,False
105,2018-02-20T00:00:00,GHCND:USC00280907,1.3,-inf,7.2,-3.3,7.2,NaN,False
106,2018-02-21T00:00:00,GHCND:USC00280907,0.0,-inf,17.8,6.1,12.8,NaN,False
107,2018-02-22T00:00:00,GHCND:USC00280907,8.6,-inf,23.9,5.6,5.6,NaN,False
108,2018-02-22T00:00:00,?,6.1,NaN,5505.0,-40.0,NaN,NaN,True
109,2018-02-23T00:00:00,GHCND:USC00280907,7.4,-inf,7.2,1.1,2.2,NaN,False
110,2018-02-23T00:00:00,GHCND:USC00280907,7.4,-inf,7.2,1.1,2.2,NaN,False
111,2018-02-23T00:00:00,?,6.1,NaN,5505.0,-40.0,NaN,NaN,True
112,2018-02-25T00:00:00,?,21.3,NaN,5505.0,-40.0,NaN,NaN,True
113,2018-02-25T00:00:00,GHCND:USC00280907,16.5,-inf,11.1,3.9,4.4,NaN,False
114,2018-02-26T00:00:00,?,3.0,NaN,5505.0,-40.0,NaN,NaN,True
115,2018-02-27T00:00:00,GHCND:USC00280907,0.0,-inf,10.6,0.0,0.0,NaN,False
116,2018-02-27T00:00:00,GHCND:USC00280907,0.0,-inf,10.6,0.0,0.0,NaN,False
117,2018-02-28T00:00:00,GHCND:USC00280907,0.0,-inf,12.2,0.0,0.0,NaN,False
118,2018-02-28T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
119,2018-02-28T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
120,2018-03-01T00:00:00,GHCND:USC00280907,0.0,-inf,14.4,0.0,3.9,NaN,False
121,2018-03-01T00:00:00,GHCND:USC00280907,0.0,-inf,14.4,0.0,3.9,NaN,False
122,2018-03-01T00:00:00,GHCND:USC00280907,0.0,-inf,14.4,0.0,3.9,NaN,False
123,2018-03-01T00:00:00,GHCND:USC00280907,0.0,-inf,14.4,0.0,3.9,NaN,False
124,2018-03-03T00:00:00,GHCND:USC00280907,25.4,NaN,2.8,0.0,1.1,NaN,False
125,2018-03-03T00:00:00,?,18.0,NaN,5505.0,-40.0,NaN,NaN,True
126,2018-03-04T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,1.1,2.8,NaN,False
127,2018-03-04T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,1.1,2.8,NaN,False
128,2018-03-04T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
129,2018-03-05T00:00:00,GHCND:USC00280907,0.0,-inf,5.6,-1.1,-1.1,NaN,False
130,2018-03-05T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
131,2018-03-06T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,-2.2,-1.7,NaN,False
132,2018-03-06T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,-2.2,-1.7,NaN,False
133,2018-03-06T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
134,2018-03-06T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,-2.2,-1.7,NaN,False
135,2018-03-08T00:00:00,GHCND:USC00280907,48.8,NaN,1.1,-0.6,1.1,NaN,False
136,2018-03-08T00:00:00,GHCND:USC00280907,48.8,NaN,1.1,-0.6,1.1,NaN,False
137,2018-03-08T00:00:00,?,28.4,NaN,5505.0,-40.0,NaN,28.7,True
138,2018-03-08T00:00:00,GHCND:USC00280907,48.8,NaN,1.1,-0.6,1.1,NaN,False
139,2018-03-09T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
140,2018-03-09T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
141,2018-03-10T00:00:00,GHCND:USC00280907,0.0,-inf,4.4,-1.7,0.0,NaN,False
142,2018-03-10T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
143,2018-03-12T00:00:00,GHCND:USC00280907,0.0,-inf,5.6,-3.9,-3.9,NaN,False
144,2018-03-12T00:00:00,GHCND:USC00280907,0.0,-inf,5.6,-3.9,-3.9,NaN,False
145,2018-03-13T00:00:00,GHCND:USC00280907,4.1,inf,5.6,-3.9,0.0,NaN,True
146,2018-03-13T00:00:00,?,3.0,inf,5505.0,-40.0,NaN,3.0,True
147,2018-03-14T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
148,2018-03-15T00:00:00,GHCND:USC00280907,0.0,-inf,3.3,-2.2,-0.6,NaN,False
149,2018-03-15T00:00:00,?,0.3,-inf,5505.0,-40.0,NaN,NaN,True
150,2018-03-16T00:00:00,GHCND:USC00280907,0.0,-inf,6.7,-1.1,-0.6,NaN,False
151,2018-03-16T00:00:00,?,1.8,NaN,5505.0,-40.0,NaN,NaN,True
152,2018-03-17T00:00:00,GHCND:USC00280907,0.0,-inf,3.9,-3.9,-3.3,NaN,False
153,2018-03-17T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
154,2018-03-18T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
155,2018-03-19T00:00:00,GHCND:USC00280907,0.0,-inf,5.0,-4.4,-3.3,NaN,False
156,2018-03-19T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
157,2018-03-19T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
158,2018-03-20T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
159,2018-03-21T00:00:00,?,6.6,inf,5505.0,-40.0,NaN,8.6,True
160,2018-03-21T00:00:00,GHCND:USC00280907,0.0,-inf,2.8,-2.8,0.6,NaN,False
161,2018-03-21T00:00:00,GHCND:USC00280907,0.0,-inf,2.8,-2.8,0.6,NaN,False
162,2018-03-21T00:00:00,?,6.6,inf,5505.0,-40.0,NaN,8.6,True
163,2018-03-22T00:00:00,GHCND:USC00280907,17.3,inf,1.7,-1.7,0.0,NaN,True
164,2018-03-22T00:00:00,GHCND:USC00280907,17.3,inf,1.7,-1.7,0.0,NaN,True
165,2018-03-23T00:00:00,GHCND:USC00280907,0.0,-inf,8.9,0.0,1.1,NaN,False
166,2018-03-23T00:00:00,?,1.8,NaN,5505.0,-40.0,NaN,NaN,True
167,2018-03-23T00:00:00,GHCND:USC00280907,0.0,-inf,8.9,0.0,1.1,NaN,False
168,2018-03-25T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
169,2018-03-25T00:00:00,GHCND:USC00280907,0.0,-inf,8.3,-1.1,-0.6,NaN,False
170,2018-03-25T00:00:00,GHCND:USC00280907,0.0,-inf,8.3,-1.1,-0.6,NaN,False
171,2018-03-26T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,-3.9,-2.2,NaN,False
172,2018-03-26T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,-3.9,-2.2,NaN,False
173,2018-03-26T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,-3.9,-2.2,NaN,False
174,2018-03-27T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
175,2018-03-27T00:00:00,GHCND:USC00280907,0.0,-inf,10.0,-3.3,-3.3,NaN,False
176,2018-03-27T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
177,2018-03-29T00:00:00,GHCND:USC00280907,0.0,-inf,10.6,1.7,7.2,NaN,False
178,2018-03-29T00:00:00,?,0.5,NaN,5505.0,-40.0,NaN,NaN,True
179,2018-03-30T00:00:00,?,0.8,NaN,5505.0,-40.0,NaN,NaN,True
180,2018-03-30T00:00:00,?,0.8,NaN,5505.0,-40.0,NaN,NaN,True
181,2018-03-31T00:00:00,?,0.3,NaN,5505.0,-40.0,NaN,NaN,True
182,2018-03-31T00:00:00,GHCND:USC00280907,1.0,-inf,13.3,1.7,2.8,NaN,False
183,2018-03-31T00:00:00,GHCND:USC00280907,1.0,-inf,13.3,1.7,2.8,NaN,False
184,2018-03-31T00:00:00,GHCND:USC00280907,1.0,-inf,13.3,1.7,2.8,NaN,False
185,2018-04-02T00:00:00,GHCND:USC00280907,9.1,inf,12.8,-1.1,-1.1,NaN,True
186,2018-04-02T00:00:00,?,14.0,inf,5505.0,-40.0,NaN,15.2,True
187,2018-04-02T00:00:00,GHCND:USC00280907,9.1,inf,12.8,-1.1,-1.1,NaN,True
188,2018-04-03T00:00:00,?,4.8,NaN,5505.0,-40.0,NaN,NaN,True
189,2018-04-03T00:00:00,?,4.8,NaN,5505.0,-40.0,NaN,NaN,True
190,2018-04-03T00:00:00,?,4.8,NaN,5505.0,-40.0,NaN,NaN,True
191,2018-04-04T00:00:00,GHCND:USC00280907,11.4,-inf,3.9,-0.6,3.9,NaN,False
192,2018-04-04T00:00:00,GHCND:USC00280907,11.4,-inf,3.9,-0.6,3.9,NaN,False
193,2018-04-04T00:00:00,GHCND:USC00280907,11.4,-inf,3.9,-0.6,3.9,NaN,False
194,2018-04-04T00:00:00,GHCND:USC00280907,11.4,-inf,3.9,-0.6,3.9,NaN,False
195,2018-04-05T00:00:00,GHCND:USC00280907,0.3,-inf,11.7,-0.6,-0.6,NaN,False
196,2018-04-05T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
197,2018-04-06T00:00:00,?,0.3,NaN,5505.0,-40.0,NaN,NaN,True
198,2018-04-07T00:00:00,GHCND:USC00280907,0.8,-inf,13.9,-1.7,2.8,NaN,False
199,2018-04-07T00:00:00,?,0.5,NaN,5505.0,-40.0,NaN,NaN,True
200,2018-04-08T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
201,2018-04-08T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
202,2018-04-09T00:00:00,GHCND:USC00280907,0.0,-inf,6.1,-2.2,-1.7,NaN,False
203,2018-04-10T00:00:00,GHCND:USC00280907,0.5,-inf,8.9,-1.7,1.7,NaN,False
204,2018-04-10T00:00:00,GHCND:USC00280907,0.5,-inf,8.9,-1.7,1.7,NaN,False
205,2018-04-11T00:00:00,GHCND:USC00280907,0.0,-inf,8.9,-3.3,-3.3,NaN,False
206,2018-04-12T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
207,2018-04-12T00:00:00,GHCND:USC00280907,0.0,-inf,10.0,-3.3,2.2,NaN,False
208,2018-04-12T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
209,2018-04-12T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
210,2018-04-13T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
211,2018-04-13T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
212,2018-04-14T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
213,2018-04-14T00:00:00,GHCND:USC00280907,0.0,-inf,26.7,11.1,12.8,NaN,False
214,2018-04-14T00:00:00,GHCND:USC00280907,0.0,-inf,26.7,11.1,12.8,NaN,False
215,2018-04-14T00:00:00,GHCND:USC00280907,0.0,-inf,26.7,11.1,12.8,NaN,False
216,2018-04-14T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
217,2018-04-15T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
218,2018-04-17T00:00:00,?,26.2,NaN,5505.0,-40.0,NaN,NaN,True
219,2018-04-18T00:00:00,GHCND:USC00280907,0.0,-inf,7.2,2.2,2.8,NaN,False
220,2018-04-18T00:00:00,GHCND:USC00280907,0.0,-inf,7.2,2.2,2.8,NaN,False
221,2018-04-19T00:00:00,?,2.5,NaN,5505.0,-40.0,NaN,NaN,True
222,2018-04-19T00:00:00,GHCND:USC00280907,6.9,-inf,11.1,2.8,3.9,NaN,False
223,2018-04-19T00:00:00,?,2.5,NaN,5505.0,-40.0,NaN,NaN,True
224,2018-04-20T00:00:00,GHCND:USC00280907,1.3,-inf,7.8,1.7,1.7,NaN,False
225,2018-04-22T00:00:00,GHCND:USC00280907,0.0,-inf,15.6,4.4,7.8,NaN,False
226,2018-04-22T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
227,2018-04-22T00:00:00,GHCND:USC00280907,0.0,-inf,15.6,4.4,7.8,NaN,False
228,2018-04-22T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
229,2018-04-23T00:00:00,GHCND:USC00280907,0.0,-inf,18.3,1.1,1.7,NaN,False
230,2018-04-24T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
231,2018-04-25T00:00:00,GHCND:USC00280907,10.2,-inf,18.9,2.2,10.6,NaN,False
232,2018-04-25T00:00:00,GHCND:USC00280907,10.2,-inf,18.9,2.2,10.6,NaN,False
233,2018-04-25T00:00:00,GHCND:USC00280907,10.2,-inf,18.9,2.2,10.6,NaN,False
234,2018-04-25T00:00:00,GHCND:USC00280907,10.2,-inf,18.9,2.2,10.6,NaN,False
235,2018-04-26T00:00:00,GHCND:USC00280907,28.4,-inf,15.0,10.6,12.2,NaN,False
236,2018-04-26T00:00:00,?,9.1,NaN,5505.0,-40.0,NaN,NaN,True
237,2018-04-27T00:00:00,?,1.0,NaN,5505.0,-40.0,NaN,NaN,True
238,2018-04-27T00:00:00,GHCND:USC00280907,0.0,-inf,20.0,8.9,10.6,NaN,False
239,2018-04-27T00:00:00,?,1.0,NaN,5505.0,-40.0,NaN,NaN,True
240,2018-04-28T00:00:00,GHCND:USC00280907,2.8,-inf,12.8,7.8,9.4,NaN,False
241,2018-04-28T00:00:00,?,1.0,NaN,5505.0,-40.0,NaN,NaN,True
242,2018-04-28T00:00:00,?,1.0,NaN,5505.0,-40.0,NaN,NaN,True
243,2018-04-29T00:00:00,?,8.9,NaN,5505.0,-40.0,NaN,NaN,True
244,2018-04-29T00:00:00,GHCND:USC00280907,9.4,-inf,21.1,8.9,8.9,NaN,False
245,2018-04-29T00:00:00,GHCND:USC00280907,9.4,-inf,21.1,8.9,8.9,NaN,False
246,2018-04-29T00:00:00,GHCND:USC00280907,9.4,-inf,21.1,8.9,8.9,NaN,False
247,2018-04-30T00:00:00,GHCND:USC00280907,0.0,-inf,13.3,7.2,7.2,NaN,False
248,2018-05-01T00:00:00,?,2.0,NaN,5505.0,-40.0,NaN,NaN,True
249,2018-05-01T00:00:00,GHCND:USC00280907,1.3,-inf,9.4,3.3,3.9,NaN,False
250,2018-05-01T00:00:00,?,2.0,NaN,5505.0,-40.0,NaN,NaN,True
251,2018-05-02T00:00:00,GHCND:USC00280907,0.0,-inf,26.1,3.9,11.1,NaN,False
252,2018-05-02T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
253,2018-05-03T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
254,2018-05-04T00:00:00,?,0.8,NaN,5505.0,-40.0,NaN,NaN,True
255,2018-05-05T00:00:00,GHCND:USC00280907,0.0,-inf,28.3,15.0,15.0,NaN,False
256,2018-05-05T00:00:00,GHCND:USC00280907,0.0,-inf,28.3,15.0,15.0,NaN,False
257,2018-05-06T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
258,2018-05-06T00:00:00,GHCND:USC00280907,0.8,-inf,23.9,13.9,13.9,NaN,False
259,2018-05-06T00:00:00,GHCND:USC00280907,0.8,-inf,23.9,13.9,13.9,NaN,False
260,2018-05-06T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
261,2018-05-07T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
262,2018-05-07T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
263,2018-05-07T00:00:00,GHCND:USC00280907,5.6,-inf,16.7,9.4,9.4,NaN,False
264,2018-05-07T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
265,2018-05-08T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
266,2018-05-09T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
267,2018-05-10T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
268,2018-05-10T00:00:00,GHCND:USC00280907,0.0,-inf,26.1,8.9,10.0,NaN,False
269,2018-05-10T00:00:00,GHCND:USC00280907,0.0,-inf,26.1,8.9,10.0,NaN,False
270,2018-05-11T00:00:00,?,8.9,NaN,5505.0,-40.0,NaN,NaN,True
271,2018-05-11T00:00:00,GHCND:USC00280907,12.2,-inf,23.3,10.0,13.9,NaN,False
272,2018-05-11T00:00:00,GHCND:USC00280907,12.2,-inf,23.3,10.0,13.9,NaN,False
273,2018-05-11T00:00:00,?,8.9,NaN,5505.0,-40.0,NaN,NaN,True
274,2018-05-12T00:00:00,?,4.8,NaN,5505.0,-40.0,NaN,NaN,True
275,2018-05-12T00:00:00,?,4.8,NaN,5505.0,-40.0,NaN,NaN,True
276,2018-05-12T00:00:00,?,4.8,NaN,5505.0,-40.0,NaN,NaN,True
277,2018-05-12T00:00:00,GHCND:USC00280907,3.0,-inf,22.2,8.9,10.0,NaN,False
278,2018-05-13T00:00:00,GHCND:USC00280907,5.1,-inf,12.8,9.4,10.6,NaN,False
279,2018-05-13T00:00:00,?,2.0,NaN,5505.0,-40.0,NaN,NaN,True
280,2018-05-14T00:00:00,GHCND:USC00280907,5.8,-inf,11.7,10.0,11.1,NaN,False
281,2018-05-15T00:00:00,?,0.0,-inf,5505.0,-40.0,NaN,NaN,True
282,2018-05-15T00:00:00,GHCND:USC00280907,0.5,-inf,23.3,10.6,17.8,NaN,False
283,2018-05-17T00:00:00,?,13.7,NaN,5505.0,-40.0,NaN,NaN,True
284,2018-05-17T00:00:00,?,13.7,NaN,5505.0,-40.0,NaN,NaN,True
285,2018-05-18T00:00:00,?,0.8,NaN,5505.0,-40.0,NaN,NaN,True
286,2018-05-19T00:00:00,?,9.7,NaN,5505.0,-40.0,NaN,NaN,True
287,2018-05-19T00:00:00,GHCND:USC00280907,3.0,-inf,18.9,7.8,8.3,NaN,False
288,2018-05-20T00:00:00,?,9.7,NaN,5505.0,-40.0,NaN,NaN,True
289,2018-05-20T00:00:00,?,9.7,NaN,5505.0,-40.0,NaN,NaN,True
290,2018-05-20T00:00:00,GHCND:USC00280907,15.2,-inf,14.4,7.8,13.9,NaN,False
291,2018-05-20T00:00:00,?,9.7,NaN,5505.0,-40.0,NaN,NaN,True
292,2018-05-20T00:00:00,?,9.7,NaN,5505.0,-40.0,NaN,NaN,True
293,2018-05-20T00:00:00,?,9.7,NaN,5505.0,-40.0,NaN,NaN,True