# Module Three Activity

You will complete your assignment code in this **Module_Three_Activity.ipynb** Notebook file from the filetree that is pre-templated for your modification in accordance with the assignment instructions.

Once your code is complete, you will download this notebook as an HTML file by clicking **File**, then **Download As**, then **HTML (.html)** from the Jupyter menu bar. You will also need to download the csv output file of your merged data. Validate that your code and outputs are rendered in the html file before submission.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Missing Blocks:</i></b> Ensure that you have clicked <b><mark>Run</mark></b> for all blocks before downloading as an HTML file or the block may be missing from your submission.</span>
</div>

### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this starter code file, replace the `data/sample_use_only/{data_name}.csv` with the reference to your selected data from the list below:

- `data/nyc_temperatures.csv`
- `data/nyc_weather_2018.csv`
- `data/parsed.csv`
- `data/quakes.db`
- `data/tsunamis.csv`
- `data/weather.db`
- `data/weather_by_station.csv`
- `data/weather_stations.csv`

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace each <b>data_file_#</b> entry sample data path with the path to your selected data sets.</span>
</div>

If you choose to only use two data files instead of three, comment out the reference to data_file_3.

In [8]:
data_file_1 = "data/nyc_temperatures.csv"
data_file_2 = "data/nyc_weather_2018.csv"
data_file_3 = "data/weather_by_station.csv"

## Installing Required Packages
If you have additional packages that you would like to use or install, add them to the **requirements.txt** file then run the next block.

In [9]:
!pip install --upgrade pip

Requirement already satisfied: pip in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (26.1.1)

In [10]:
!pip install -r requirements.txt

Requirement already satisfied: ydata-profiling==4.16.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: pydantic>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.30.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.14.6)
Requirement already satisfied: typeguard<5,>=3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.5.2)
Requirement already satisfied: imagehash==4.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.6)
Requirement already satisfied: dacite>=1.8 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.61.0)
Requirement already satisfied: PyWavelets in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: pillow in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from phik<0.13,>=0.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.5.7)
Requirement already satisfied: patsy>=0.5.6 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: typing_extensions>=4.14.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from typeguard<5,>=3->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: attrs>=19.3.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: puremagic in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.30)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: six>=1.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.16.0)

## Import the Required Packages
If you have additional packages that you would like to import, add them here.

In [11]:
import pandas as pd
import numpy as np

## Loading and Preprocessing the Data
After you have selected your data set that wish to wrangle, replace the reference file path in the code block at the top of this Notebook, then run the following blocks.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need to preprocess or clean your dataset before merging.</span>
</div>

### Data File 1 dataframe
Here we will load the data_file_1 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [12]:
data1 = pd.read_csv(data_file_1)
data1.head()

                  date datatype            station attributes  value
0  2018-10-01T00:00:00     TAVG  GHCND:USW00014732      H,,S,   21.2
1  2018-10-01T00:00:00     TMAX  GHCND:USW00014732   ,,W,2400   25.6
2  2018-10-01T00:00:00     TMIN  GHCND:USW00014732   ,,W,2400   18.3
3  2018-10-02T00:00:00     TAVG  GHCND:USW00014732      H,,S,   22.7
4  2018-10-02T00:00:00     TMAX  GHCND:USW00014732   ,,W,2400   26.1

In [15]:
data1_wide = data1.pivot(index=['date','datatype','station'], columns='attributes', values='value')
data1_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 93 entries, ('2018-10-01T00:00:00', 'TAVG', 'GHCND:USW00014732') to ('2018-10-31T00:00:00', 'TMIN', 'GHCND:USW00014732')
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ,,W,2400  62 non-null     float64
 1   H,,S,     31 non-null     float64
dtypes: float64(2)
memory usage: 3.4+ KB

In [16]:
data1_wide.dropna(thresh=40, axis=1, inplace=True)
data1_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 93 entries, ('2018-10-01T00:00:00', 'TAVG', 'GHCND:USW00014732') to ('2018-10-31T00:00:00', 'TMIN', 'GHCND:USW00014732')
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ,,W,2400  62 non-null     float64
dtypes: float64(1)
memory usage: 2.7+ KB

In [17]:
data1_wide.fillna(value=0, inplace=True)
data1_wide

attributes                                      ,,W,2400
date                datatype station
2018-10-01T00:00:00 TAVG     GHCND:USW00014732       0.0
                    TMAX     GHCND:USW00014732      25.6
                    TMIN     GHCND:USW00014732      18.3
2018-10-02T00:00:00 TAVG     GHCND:USW00014732       0.0
                    TMAX     GHCND:USW00014732      26.1
...                                                  ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732      13.9
                    TMIN     GHCND:USW00014732       7.2
2018-10-31T00:00:00 TAVG     GHCND:USW00014732       0.0
                    TMAX     GHCND:USW00014732      17.8
                    TMIN     GHCND:USW00014732       7.2

[93 rows x 1 columns]

### Data File 2 dataframe
Here we will load the data_file_2 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [18]:
data2 = pd.read_csv(data_file_2)
data2.head()

                  date datatype            station attributes  value
0  2018-01-01T00:00:00     PRCP  GHCND:US1CTFR0039       ,,N,    0.0
1  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0015       ,,N,    0.0
2  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0015       ,,N,    0.0
3  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0017       ,,N,    0.0
4  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0017       ,,N,    0.0

In [23]:
data2.rename(columns={'Data Type': 'datatype', 'Station': 'station'}, inplace=True)
data2.head()

                  date datatype            station attributes  value
0  2018-01-01T00:00:00     PRCP  GHCND:US1CTFR0039       ,,N,    0.0
1  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0015       ,,N,    0.0
2  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0015       ,,N,    0.0
3  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0017       ,,N,    0.0
4  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0017       ,,N,    0.0

In [31]:
data2_wide = data2.pivot(index=['date','datatype','station'], columns='attributes', values='value')
data2_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 78780 entries, ('2018-01-01T00:00:00', 'AWND', 'GHCND:USW00014732') to ('2018-12-31T00:00:00', 'WT02', 'GHCND:USW00094789')
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ,,7,       2679 non-null   float64
 1   ,,7,0630   715 non-null    float64
 2   ,,7,0700   8534 non-null   float64
 3   ,,7,0800   1034 non-null   float64
 4   ,,N,       34153 non-null  float64
 5   ,,N,0700   4 non-null      float64
 6   ,,W,       21241 non-null  float64
 7   ,,W,2400   6641 non-null   float64
 8   ,,Z,       7 non-null      float64
 9   ,,Z,0700   2 non-null      float64
 10  ,G,7,0800  1 non-null      float64
 11  ,I,N,      5 non-null      float64
 12  ,L,N,      29 non-null     float64
 13  ,S,W,2400  1 non-null      float64
 14  ,Z,7,      2 non-null      float64
 15  ,Z,7,0700  6 non-null      float64
 16  ,Z,W,      4 non-null      float64
 17  H,,S,      1095 non-null   float64
 18  T,,7,      50 non-null     float64
 19  T,,7,0630  6 non-null      float64
 20  T,,7,0700  137 non-null    float64
 21  T,,N,      1886 non-null   float64
 22  T,,N,0700  3 non-null      float64
 23  T,,W,      250 non-null    float64
 24  T,,W,2400  293 non-null    float64
 25  T,I,N,     2 non-null      float64
dtypes: float64(26)
memory usage: 15.9+ MB

In [32]:
data2_wide

attributes                                      ,,7,  ,,7,0630  ,,7,0700
date                datatype station
2018-01-01T00:00:00 AWND     GHCND:USW00014732   NaN       NaN       NaN  \
                             GHCND:USW00014734   NaN       NaN       NaN
                             GHCND:USW00054743   NaN       NaN       NaN
                             GHCND:USW00054787   NaN       NaN       NaN
                             GHCND:USW00094728   NaN       NaN       NaN
...                                              ...       ...       ...
2018-12-31T00:00:00 WT01     GHCND:USW00014732   NaN       NaN       NaN
                             GHCND:USW00014734   NaN       NaN       NaN
                             GHCND:USW00094728   NaN       NaN       NaN
                             GHCND:USW00094789   NaN       NaN       NaN
                    WT02     GHCND:USW00094789   NaN       NaN       NaN

attributes                                      ,,7,0800  ,,N,  ,,N,0700
date                datatype station
2018-01-01T00:00:00 AWND     GHCND:USW00014732       NaN   NaN       NaN  \
                             GHCND:USW00014734       NaN   NaN       NaN
                             GHCND:USW00054743       NaN   NaN       NaN
                             GHCND:USW00054787       NaN   NaN       NaN
                             GHCND:USW00094728       NaN   NaN       NaN
...                                                  ...   ...       ...
2018-12-31T00:00:00 WT01     GHCND:USW00014732       NaN   NaN       NaN
                             GHCND:USW00014734       NaN   NaN       NaN
                             GHCND:USW00094728       NaN   NaN       NaN
                             GHCND:USW00094789       NaN   NaN       NaN
                    WT02     GHCND:USW00094789       NaN   NaN       NaN

attributes                                      ,,W,  ,,W,2400  ,,Z,
date                datatype station
2018-01-01T00:00:00 AWND     GHCND:USW00014732   7.6       NaN   NaN  \
                             GHCND:USW00014734   5.7       NaN   NaN
                             GHCND:USW00054743   2.9       NaN   NaN
                             GHCND:USW00054787   3.8       NaN   NaN
                             GHCND:USW00094728   3.5       NaN   NaN
...                                              ...       ...   ...
2018-12-31T00:00:00 WT01     GHCND:USW00014732   1.0       NaN   NaN
                             GHCND:USW00014734   1.0       NaN   NaN
                             GHCND:USW00094728   1.0       NaN   NaN
                             GHCND:USW00094789   1.0       NaN   NaN
                    WT02     GHCND:USW00094789   1.0       NaN   NaN

attributes                                      ,,Z,0700  ...  ,Z,W,  H,,S,
date                datatype station                      ...
2018-01-01T00:00:00 AWND     GHCND:USW00014732       NaN  ...    NaN    NaN  \
                             GHCND:USW00014734       NaN  ...    NaN    NaN
                             GHCND:USW00054743       NaN  ...    NaN    NaN
                             GHCND:USW00054787       NaN  ...    NaN    NaN
                             GHCND:USW00094728       NaN  ...    NaN    NaN
...                                                  ...  ...    ...    ...
2018-12-31T00:00:00 WT01     GHCND:USW00014732       NaN  ...    NaN    NaN
                             GHCND:USW00014734       NaN  ...    NaN    NaN
                             GHCND:USW00094728       NaN  ...    NaN    NaN
                             GHCND:USW00094789       NaN  ...    NaN    NaN
                    WT02     GHCND:USW00094789       NaN  ...    NaN    NaN

attributes                                      T,,7,  T,,7,0630  T,,7,0700
date                datatype station
2018-01-01T00:00:00 AWND     GHCND:USW00014732    NaN        NaN        NaN  \
                             GHCND:USW00014734    NaN        NaN        NaN
                             GHCND:USW00054743    NaN        NaN        NaN
                             GHCND:USW00054787    NaN        NaN        NaN
                             GHCND:USW00094728    NaN        NaN        NaN
...                                               ...        ...        ...
2018-12-31T00:00:00 WT01     GHCND:USW00014732    NaN        NaN        NaN
                             GHCND:USW00014734    NaN        NaN        NaN
                             GHCND:USW00094728    NaN        NaN        NaN
                             GHCND:USW00094789    NaN        NaN        NaN
                    WT02     GHCND:USW00094789    NaN        NaN        NaN

attributes                                      T,,N,  T,,N,0700  T,,W,
date                datatype station
2018-01-01T00:00:00 AWND     GHCND:USW00014732    NaN        NaN    NaN  \
                             GHCND:USW00014734    NaN        NaN    NaN
                             GHCND:USW00054743    NaN        NaN    NaN
                             GHCND:USW00054787    NaN        NaN    NaN
                             GHCND:USW00094728    NaN        NaN    NaN
...                                               ...        ...    ...
2018-12-31T00:00:00 WT01     GHCND:USW00014732    NaN        NaN    NaN
                             GHCND:USW00014734    NaN        NaN    NaN
                             GHCND:USW00094728    NaN        NaN    NaN
                             GHCND:USW00094789    NaN        NaN    NaN
                    WT02     GHCND:USW00094789    NaN        NaN    NaN

attributes                                      T,,W,2400  T,I,N,
date                datatype station
2018-01-01T00:00:00 AWND     GHCND:USW00014732        NaN     NaN
                             GHCND:USW00014734        NaN     NaN
                             GHCND:USW00054743        NaN     NaN
                             GHCND:USW00054787        NaN     NaN
                             GHCND:USW00094728        NaN     NaN
...                                                   ...     ...
2018-12-31T00:00:00 WT01     GHCND:USW00014732        NaN     NaN
                             GHCND:USW00014734        NaN     NaN
                             GHCND:USW00094728        NaN     NaN
                             GHCND:USW00094789        NaN     NaN
                    WT02     GHCND:USW00094789        NaN     NaN

[78780 rows x 26 columns]

### Data File 3 dataframe
If you choose not to included a third file for merging, remove or comment out the blocks for data3.

Here we will load the data_file_3 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [33]:
data3 = pd.read_csv(data_file_3)
data3.head()

,date,datatype,station,value,station_name
0,2018-01-01,PRCP,GHCND:US1CTFR0039,0.0,"STAMFORD 4.2 S, CT US"
1,2018-01-01,PRCP,GHCND:US1NJBG0015,0.0,"NORTH ARLINGTON 0.7 WNW, NJ US"
2,2018-01-01,SNOW,GHCND:US1NJBG0015,0.0,"NORTH ARLINGTON 0.7 WNW, NJ US"
3,2018-01-01,PRCP,GHCND:US1NJBG0017,0.0,"GLEN ROCK 0.7 SSE, NJ US"
4,2018-01-01,SNOW,GHCND:US1NJBG0017,0.0,"GLEN ROCK 0.7 SSE, NJ US"

In [34]:
data3.rename(columns={'Date': 'date'}, inplace=True)
data3.head()

,date,datatype,station,value,station_name
0,2018-01-01,PRCP,GHCND:US1CTFR0039,0.0,"STAMFORD 4.2 S, CT US"
1,2018-01-01,PRCP,GHCND:US1NJBG0015,0.0,"NORTH ARLINGTON 0.7 WNW, NJ US"
2,2018-01-01,SNOW,GHCND:US1NJBG0015,0.0,"NORTH ARLINGTON 0.7 WNW, NJ US"
3,2018-01-01,PRCP,GHCND:US1NJBG0017,0.0,"GLEN ROCK 0.7 SSE, NJ US"
4,2018-01-01,SNOW,GHCND:US1NJBG0017,0.0,"GLEN ROCK 0.7 SSE, NJ US"

In [39]:
data3_wide = data3.pivot(index=['date','datatype','station'], columns='station_name', values='value')
data3_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 80256 entries, ('2018-01-01', 'AWND', 'GHCND:USW00014732') to ('2018-12-31', 'WT02', 'GHCND:USW00094789')
Columns: 109 entries, ALBERTSON 0.2 SSE, NY US to WOODBRIDGE TWP 3.0 NNW, NJ US
dtypes: float64(109)
memory usage: 67.1+ MB

In [40]:
data3_wide.dropna(thresh=40, axis=1, inplace=True)
data3_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 80256 entries, ('2018-01-01', 'AWND', 'GHCND:USW00014732') to ('2018-12-31', 'WT02', 'GHCND:USW00094789')
Columns: 106 entries, ALBERTSON 0.2 SSE, NY US to WOODBRIDGE TWP 3.0 NNW, NJ US
dtypes: float64(106)
memory usage: 65.2+ MB

In [41]:
data3_wide.fillna(value=0, inplace=True)
data3_wide

station_name                           ALBERTSON 0.2 SSE, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                       0.0  \
                    GHCND:USW00014734                       0.0
                    GHCND:USW00054743                       0.0
                    GHCND:USW00054787                       0.0
                    GHCND:USW00094728                       0.0
...                                                         ...
2018-12-31 WT01     GHCND:USW00014732                       0.0
                    GHCND:USW00014734                       0.0
                    GHCND:USW00094728                       0.0
                    GHCND:USW00094789                       0.0
           WT02     GHCND:USW00094789                       0.0

station_name                           AMITYVILLE 0.1 WSW, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                        0.0  \
                    GHCND:USW00014734                        0.0
                    GHCND:USW00054743                        0.0
                    GHCND:USW00054787                        0.0
                    GHCND:USW00094728                        0.0
...                                                          ...
2018-12-31 WT01     GHCND:USW00014732                        0.0
                    GHCND:USW00014734                        0.0
                    GHCND:USW00094728                        0.0
                    GHCND:USW00094789                        0.0
           WT02     GHCND:USW00094789                        0.0

station_name                           AMITYVILLE 0.6 NNE, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                        0.0  \
                    GHCND:USW00014734                        0.0
                    GHCND:USW00054743                        0.0
                    GHCND:USW00054787                        0.0
                    GHCND:USW00094728                        0.0
...                                                          ...
2018-12-31 WT01     GHCND:USW00014732                        0.0
                    GHCND:USW00014734                        0.0
                    GHCND:USW00094728                        0.0
                    GHCND:USW00094789                        0.0
           WT02     GHCND:USW00094789                        0.0

station_name                           ARMONK 0.3 SE, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                   0.0  \
                    GHCND:USW00014734                   0.0
                    GHCND:USW00054743                   0.0
                    GHCND:USW00054787                   0.0
                    GHCND:USW00094728                   0.0
...                                                     ...
2018-12-31 WT01     GHCND:USW00014732                   0.0
                    GHCND:USW00014734                   0.0
                    GHCND:USW00094728                   0.0
                    GHCND:USW00094789                   0.0
           WT02     GHCND:USW00094789                   0.0

station_name                           BLOOMINGDALE 0.7 SSE, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                          0.0  \
                    GHCND:USW00014734                          0.0
                    GHCND:USW00054743                          0.0
                    GHCND:USW00054787                          0.0
                    GHCND:USW00094728                          0.0
...                                                            ...
2018-12-31 WT01     GHCND:USW00014732                          0.0
                    GHCND:USW00014734                          0.0
                    GHCND:USW00094728                          0.0
                    GHCND:USW00094789                          0.0
           WT02     GHCND:USW00094789                          0.0

station_name                           BOONTON 0.6 NW, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                    0.0  \
                    GHCND:USW00014734                    0.0
                    GHCND:USW00054743                    0.0
                    GHCND:USW00054787                    0.0
                    GHCND:USW00094728                    0.0
...                                                      ...
2018-12-31 WT01     GHCND:USW00014732                    0.0
                    GHCND:USW00014734                    0.0
                    GHCND:USW00094728                    0.0
                    GHCND:USW00094789                    0.0
           WT02     GHCND:USW00094789                    0.0

station_name                           BOONTON 0.7 WSW, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                     0.0  \
                    GHCND:USW00014734                     0.0
                    GHCND:USW00054743                     0.0
                    GHCND:USW00054787                     0.0
                    GHCND:USW00094728                     0.0
...                                                       ...
2018-12-31 WT01     GHCND:USW00014732                     0.0
                    GHCND:USW00014734                     0.0
                    GHCND:USW00094728                     0.0
                    GHCND:USW00094789                     0.0
           WT02     GHCND:USW00094789                     0.0

station_name                           BOONTON 1 SE, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                  0.0  \
                    GHCND:USW00014734                  0.0
                    GHCND:USW00054743                  0.0
                    GHCND:USW00054787                  0.0
                    GHCND:USW00094728                  0.0
...                                                    ...
2018-12-31 WT01     GHCND:USW00014732                  0.0
                    GHCND:USW00014734                  0.0
                    GHCND:USW00094728                  0.0
                    GHCND:USW00094789                  0.0
           WT02     GHCND:USW00094789                  0.0

station_name                           BROOKLYN 3.1 NW, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                     0.0  \
                    GHCND:USW00014734                     0.0
                    GHCND:USW00054743                     0.0
                    GHCND:USW00054787                     0.0
                    GHCND:USW00094728                     0.0
...                                                       ...
2018-12-31 WT01     GHCND:USW00014732                     0.0
                    GHCND:USW00014734                     0.0
                    GHCND:USW00094728                     0.0
                    GHCND:USW00094789                     0.0
           WT02     GHCND:USW00094789                     0.0

station_name                           CALDWELL ESSEX CO AIRPORT, NJ US  ...
date       datatype station                                              ...
2018-01-01 AWND     GHCND:USW00014732                               0.0  ...  \
                    GHCND:USW00014734                               0.0  ...
                    GHCND:USW00054743                               2.9  ...
                    GHCND:USW00054787                               0.0  ...
                    GHCND:USW00094728                               0.0  ...
...                                                                 ...  ...
2018-12-31 WT01     GHCND:USW00014732                               0.0  ...
                    GHCND:USW00014734                               0.0  ...
                    GHCND:USW00094728                               0.0  ...
                    GHCND:USW00094789                               0.0  ...
           WT02     GHCND:USW00094789                               0.0  ...

station_name                           WANTAGH 0.3 ESE, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                     0.0  \
                    GHCND:USW00014734                     0.0
                    GHCND:USW00054743                     0.0
                    GHCND:USW00054787                     0.0
                    GHCND:USW00094728                     0.0
...                                                       ...
2018-12-31 WT01     GHCND:USW00014732                     0.0
                    GHCND:USW00014734                     0.0
                    GHCND:USW00094728                     0.0
                    GHCND:USW00094789                     0.0
           WT02     GHCND:USW00094789                     0.0

station_name                           WANTAGH 1.1 NNE, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                     0.0  \
                    GHCND:USW00014734                     0.0
                    GHCND:USW00054743                     0.0
                    GHCND:USW00054787                     0.0
                    GHCND:USW00094728                     0.0
...                                                       ...
2018-12-31 WT01     GHCND:USW00014732                     0.0
                    GHCND:USW00014734                     0.0
                    GHCND:USW00094728                     0.0
                    GHCND:USW00094789                     0.0
           WT02     GHCND:USW00094789                     0.0

station_name                           WAYNE TWP 0.8 SSW, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                       0.0  \
                    GHCND:USW00014734                       0.0
                    GHCND:USW00054743                       0.0
                    GHCND:USW00054787                       0.0
                    GHCND:USW00094728                       0.0
...                                                         ...
2018-12-31 WT01     GHCND:USW00014732                       0.0
                    GHCND:USW00014734                       0.0
                    GHCND:USW00094728                       0.0
                    GHCND:USW00094789                       0.0
           WT02     GHCND:USW00094789                       0.0

station_name                           WEST CALDWELL TWP 1.3 NE, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                              0.0  \
                    GHCND:USW00014734                              0.0
                    GHCND:USW00054743                              0.0
                    GHCND:USW00054787                              0.0
                    GHCND:USW00094728                              0.0
...                                                                ...
2018-12-31 WT01     GHCND:USW00014732                              0.0
                    GHCND:USW00014734                              0.0
                    GHCND:USW00094728                              0.0
                    GHCND:USW00094789                              0.0
           WT02     GHCND:USW00094789                              0.0

station_name                           WEST NYACK 1.3 WSW, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                        0.0  \
                    GHCND:USW00014734                        0.0
                    GHCND:USW00054743                        0.0
                    GHCND:USW00054787                        0.0
                    GHCND:USW00094728                        0.0
...                                                          ...
2018-12-31 WT01     GHCND:USW00014732                        0.0
                    GHCND:USW00014734                        0.0
                    GHCND:USW00094728                        0.0
                    GHCND:USW00094789                        0.0
           WT02     GHCND:USW00094789                        0.0

station_name                           WESTCHESTER CO AIRPORT, NY US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                            0.0  \
                    GHCND:USW00014734                            0.0
                    GHCND:USW00054743                            0.0
                    GHCND:USW00054787                            0.0
                    GHCND:USW00094728                            0.0
...                                                              ...
2018-12-31 WT01     GHCND:USW00014732                            0.0
                    GHCND:USW00014734                            0.0
                    GHCND:USW00094728                            0.0
                    GHCND:USW00094789                            0.0
           WT02     GHCND:USW00094789                            0.0

station_name                           WESTFIELD 0.6 NE, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                      0.0  \
                    GHCND:USW00014734                      0.0
                    GHCND:USW00054743                      0.0
                    GHCND:USW00054787                      0.0
                    GHCND:USW00094728                      0.0
...                                                        ...
2018-12-31 WT01     GHCND:USW00014732                      0.0
                    GHCND:USW00014734                      0.0
                    GHCND:USW00094728                      0.0
                    GHCND:USW00094789                      0.0
           WT02     GHCND:USW00094789                      0.0

station_name                           WOODBRIDGE TWP 1.1 ESE, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                            0.0  \
                    GHCND:USW00014734                            0.0
                    GHCND:USW00054743                            0.0
                    GHCND:USW00054787                            0.0
                    GHCND:USW00094728                            0.0
...                                                              ...
2018-12-31 WT01     GHCND:USW00014732                            0.0
                    GHCND:USW00014734                            0.0
                    GHCND:USW00094728                            0.0
                    GHCND:USW00094789                            0.0
           WT02     GHCND:USW00094789                            0.0

station_name                           WOODBRIDGE TWP 1.1 NNE, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                            0.0  \
                    GHCND:USW00014734                            0.0
                    GHCND:USW00054743                            0.0
                    GHCND:USW00054787                            0.0
                    GHCND:USW00094728                            0.0
...                                                              ...
2018-12-31 WT01     GHCND:USW00014732                            0.0
                    GHCND:USW00014734                            0.0
                    GHCND:USW00094728                            0.0
                    GHCND:USW00094789                            0.0
           WT02     GHCND:USW00094789                            0.0

station_name                           WOODBRIDGE TWP 3.0 NNW, NJ US
date       datatype station
2018-01-01 AWND     GHCND:USW00014732                            0.0
                    GHCND:USW00014734                            0.0
                    GHCND:USW00054743                            0.0
                    GHCND:USW00054787                            0.0
                    GHCND:USW00094728                            0.0
...                                                              ...
2018-12-31 WT01     GHCND:USW00014732                            0.0
                    GHCND:USW00014734                            0.0
                    GHCND:USW00094728                            0.0
                    GHCND:USW00094789                            0.0
           WT02     GHCND:USW00094789                            0.0

[80256 rows x 106 columns]

### Data Merging
Here is the example of a merge of the three sample files. You will need to adjust these blocks for how you wish to merge your selected data files.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need merge your dataset.</span>
</div>

In [43]:
merged_data_1_2 = pd.merge(data1_wide, data2_wide, on=['date', 'datatype', 'station'])
merged_data_1_2

attributes                                      ,,W,2400_x  ,,7,  ,,7,0630
date                datatype station
2018-10-01T00:00:00 TAVG     GHCND:USW00014732         0.0   NaN       NaN  \
                    TMAX     GHCND:USW00014732        25.6   NaN       NaN
                    TMIN     GHCND:USW00014732        18.3   NaN       NaN
2018-10-02T00:00:00 TAVG     GHCND:USW00014732         0.0   NaN       NaN
                    TMAX     GHCND:USW00014732        26.1   NaN       NaN
...                                                    ...   ...       ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732        13.9   NaN       NaN
                    TMIN     GHCND:USW00014732         7.2   NaN       NaN
2018-10-31T00:00:00 TAVG     GHCND:USW00014732         0.0   NaN       NaN
                    TMAX     GHCND:USW00014732        17.8   NaN       NaN
                    TMIN     GHCND:USW00014732         7.2   NaN       NaN

attributes                                      ,,7,0700  ,,7,0800  ,,N,
date                datatype station
2018-10-01T00:00:00 TAVG     GHCND:USW00014732       NaN       NaN   NaN  \
                    TMAX     GHCND:USW00014732       NaN       NaN   NaN
                    TMIN     GHCND:USW00014732       NaN       NaN   NaN
2018-10-02T00:00:00 TAVG     GHCND:USW00014732       NaN       NaN   NaN
                    TMAX     GHCND:USW00014732       NaN       NaN   NaN
...                                                  ...       ...   ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732       NaN       NaN   NaN
                    TMIN     GHCND:USW00014732       NaN       NaN   NaN
2018-10-31T00:00:00 TAVG     GHCND:USW00014732       NaN       NaN   NaN
                    TMAX     GHCND:USW00014732       NaN       NaN   NaN
                    TMIN     GHCND:USW00014732       NaN       NaN   NaN

attributes                                      ,,N,0700  ,,W,  ,,W,2400_y
date                datatype station
2018-10-01T00:00:00 TAVG     GHCND:USW00014732       NaN   NaN         NaN  \
                    TMAX     GHCND:USW00014732       NaN   NaN        25.6
                    TMIN     GHCND:USW00014732       NaN   NaN        18.3
2018-10-02T00:00:00 TAVG     GHCND:USW00014732       NaN   NaN         NaN
                    TMAX     GHCND:USW00014732       NaN   NaN        26.1
...                                                  ...   ...         ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732       NaN   NaN        13.9
                    TMIN     GHCND:USW00014732       NaN   NaN         7.2
2018-10-31T00:00:00 TAVG     GHCND:USW00014732       NaN   NaN         NaN
                    TMAX     GHCND:USW00014732       NaN   NaN        17.8
                    TMIN     GHCND:USW00014732       NaN   NaN         7.2

attributes                                      ,,Z,  ...  ,Z,W,  H,,S,
date                datatype station                  ...
2018-10-01T00:00:00 TAVG     GHCND:USW00014732   NaN  ...    NaN   21.2  \
                    TMAX     GHCND:USW00014732   NaN  ...    NaN    NaN
                    TMIN     GHCND:USW00014732   NaN  ...    NaN    NaN
2018-10-02T00:00:00 TAVG     GHCND:USW00014732   NaN  ...    NaN   22.7
                    TMAX     GHCND:USW00014732   NaN  ...    NaN    NaN
...                                              ...  ...    ...    ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732   NaN  ...    NaN    NaN
                    TMIN     GHCND:USW00014732   NaN  ...    NaN    NaN
2018-10-31T00:00:00 TAVG     GHCND:USW00014732   NaN  ...    NaN   12.6
                    TMAX     GHCND:USW00014732   NaN  ...    NaN    NaN
                    TMIN     GHCND:USW00014732   NaN  ...    NaN    NaN

attributes                                      T,,7,  T,,7,0630  T,,7,0700
date                datatype station
2018-10-01T00:00:00 TAVG     GHCND:USW00014732    NaN        NaN        NaN  \
                    TMAX     GHCND:USW00014732    NaN        NaN        NaN
                    TMIN     GHCND:USW00014732    NaN        NaN        NaN
2018-10-02T00:00:00 TAVG     GHCND:USW00014732    NaN        NaN        NaN
                    TMAX     GHCND:USW00014732    NaN        NaN        NaN
...                                               ...        ...        ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732    NaN        NaN        NaN
                    TMIN     GHCND:USW00014732    NaN        NaN        NaN
2018-10-31T00:00:00 TAVG     GHCND:USW00014732    NaN        NaN        NaN
                    TMAX     GHCND:USW00014732    NaN        NaN        NaN
                    TMIN     GHCND:USW00014732    NaN        NaN        NaN

attributes                                      T,,N,  T,,N,0700  T,,W,
date                datatype station
2018-10-01T00:00:00 TAVG     GHCND:USW00014732    NaN        NaN    NaN  \
                    TMAX     GHCND:USW00014732    NaN        NaN    NaN
                    TMIN     GHCND:USW00014732    NaN        NaN    NaN
2018-10-02T00:00:00 TAVG     GHCND:USW00014732    NaN        NaN    NaN
                    TMAX     GHCND:USW00014732    NaN        NaN    NaN
...                                               ...        ...    ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732    NaN        NaN    NaN
                    TMIN     GHCND:USW00014732    NaN        NaN    NaN
2018-10-31T00:00:00 TAVG     GHCND:USW00014732    NaN        NaN    NaN
                    TMAX     GHCND:USW00014732    NaN        NaN    NaN
                    TMIN     GHCND:USW00014732    NaN        NaN    NaN

attributes                                      T,,W,2400  T,I,N,
date                datatype station
2018-10-01T00:00:00 TAVG     GHCND:USW00014732        NaN     NaN
                    TMAX     GHCND:USW00014732        NaN     NaN
                    TMIN     GHCND:USW00014732        NaN     NaN
2018-10-02T00:00:00 TAVG     GHCND:USW00014732        NaN     NaN
                    TMAX     GHCND:USW00014732        NaN     NaN
...                                                   ...     ...
2018-10-30T00:00:00 TMAX     GHCND:USW00014732        NaN     NaN
                    TMIN     GHCND:USW00014732        NaN     NaN
2018-10-31T00:00:00 TAVG     GHCND:USW00014732        NaN     NaN
                    TMAX     GHCND:USW00014732        NaN     NaN
                    TMIN     GHCND:USW00014732        NaN     NaN

[93 rows x 27 columns]

In [46]:
final_merged_data = pd.merge(data3_wide, merged_data_1_2, on=['date', 'datatype', 'station'])
final_merged_data

Empty DataFrame
Columns: [ALBERTSON 0.2 SSE, NY US, AMITYVILLE 0.1 WSW, NY US, AMITYVILLE 0.6 NNE, NY US, ARMONK 0.3 SE, NY US, BLOOMINGDALE 0.7 SSE, NJ US, BOONTON 0.6 NW, NJ US, BOONTON 0.7 WSW, NJ US, BOONTON 1 SE, NJ US, BROOKLYN 3.1 NW, NY US, CALDWELL ESSEX CO AIRPORT, NJ US, CANOE BROOK, NJ US, CARTERET 0.6 WSW, NJ US, CEDAR GROVE TWP 0.4 W, NJ US, CENTERPORT 0.9 SW, NY US, CENTERPORT, NY US, CHATHAM 0.6 NW, NJ US, CHATHAM TWP 1.1 NNW, NJ US, CHATHAM TWP 2.0 NNW, NJ US, COLTS NECK TWP 2.4 NW, NJ US, COPIAGUE 0.4 ENE, NY US, CRANFORD TWP 1.1 NNW, NJ US, EATONTOWN 1.2 NE, NJ US, EDISON TWP 1.9 N, NJ US, ELMSFORD 0.8 SSW, NY US, FARMINGDALE REPUBLIC AIRPORT, NY US, FLORAL PARK 0.4 W, NY US, FLORHAM PARK 0.2 WNW, NJ US, GLEN ROCK 0.4 WNW, NJ US, GLEN ROCK 0.7 SSE, NJ US, HARRISON 0.3 N, NJ US, HARRISON, NJ US, HAWTHORNE 0.4 S, NJ US, HAWTHORNE 1.0 SSE, NJ US, HICKSVILLE 1.3 ENE, NY US, HIGHLAND PARK 0.4 N, NJ US, HIGHLAND PARK 0.5 E, NJ US, JACKSON HEIGHTS 0.3 WSW, NY US, JFK INTERNATIONAL AIRPORT, NY US, KEARNY 1.7 NW, NJ US, LA GUARDIA AIRPORT, NY US, LINDEN 2.2 NW, NJ US, LITTLE FALLS TWP 0.2 NE, NJ US, LITTLE FALLS TWP 0.5 WNW, NJ US, LOCUST VALLEY 0.3 E, NY US, LONG BRANCH 0.5 W, NJ US, LONG BRANCH 1.7 SSW, NJ US, LONG BRANCH OAKHURST, NJ US, LYNBROOK 0.3 NW, NY US, LYNBROOK 0.6 ENE, NY US, MADISON 0.8 WSW, NJ US, MAPLEWOOD TWP 0.9 SE, NJ US, MASSAPEQUA 0.9 SSW, NY US, MASSAPEQUA PARK 1.2 N, NY US, MATAWAN 1.1 WSW, NJ US, MELVILLE 1.6 SW, NY US, METUCHEN 0.5 E, NJ US, MIDDLE VILLAGE 0.5 SW, NY US, MIDDLETOWN TWP 3.6 NW, NJ US, MONTCLAIR 0.7 N, NJ US, MORRIS TWP 2.8 SE, NJ US, MORRISTOWN 1.4 E, NJ US, NEW BRUNSWICK 1.8 E, NJ US, NEW HYDE PARK 1.6 NE, NY US, NEW PROVIDENCE 0.8 ESE, NJ US, NEW YORK 8.8 N, NY US, NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US, NORTH ARLINGTON 0.7 WNW, NJ US, NORTH WANTAGH 0.4 WSW, NY US, NY CITY CENTRAL PARK, NY US, OAKLAND 0.9 SSE, NJ US, OAKLAND 1.0 ESE, NJ US, OLD BRIDGE TWP 5.1 NE, NJ US, PALISADES PARK 0.2 WNW, NJ US, PARSIPPANY TROY HILLS TWP 1.3, NJ US, PARSIPPANY TROY HILLS TWP 1.5, NJ US, PLAINEDGE 0.4 WSW, NY US, PLAINVIEW 0.4 ENE, NY US, PORT WASHINGTON 0.8 N, NY US, PUTNAM LAKE, CT US, RED BANK 0.6 ENE, NJ US, RINGWOOD 3.0 SSE, NJ US, RIVER EDGE 0.4 NNE, NJ US, RIVER VALE TWP 1.5 S, NJ US, SADDLE ROCK 3.4 WSW, NY US, SOUTH PLAINFIELD 0.7 NNE, NJ US, SPRINGFIELD TWP 0.7 NNE, NJ US, STAMFORD 4.2 S, CT US, STATEN ISLAND 1.4 SE, NY US, STATEN ISLAND 4.5 SSE, NY US, SYOSSET 2.0 SSW, NY US, SYOSSET, NY US, TENAFLY 1.3 W, NJ US, TENAFLY 1.6 NW, NJ US, TETERBORO AIRPORT, NJ US, VALLEY STREAM 0.6 SE, NY US, WANAQUE RAYMOND DAM, NJ US, WANTAGH 0.3 ESE, NY US, WANTAGH 1.1 NNE, NY US, WAYNE TWP 0.8 SSW, NJ US, WEST CALDWELL TWP 1.3 NE, NJ US, ...]
Index: []

[0 rows x 133 columns]

### Data Output

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you want to output your merged dataset.</span>
</div>

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>Data Output:</i></b> replace the output path <b><mark>'data/sample_use_only/sample_output/sample_merged_data.csv'</mark></b> with your path <b><mark>'data/{your_merged_data.csv}'</mark></b>.</span>
</div>

In [54]:
final_merged_data.to_csv('data/weather_datas.csv')